spring:
  application:
    name: chatGraph
  data:
    neo4j:
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD}
  datasource:
    url: jdbc:mariadb://localhost:3306/user
    username: chatgraph
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1
  model:
    default: gpt-4.1-nano
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000

debug: true
