# application.yml (공통 설정)
spring:
  application:
    name: chatGraph
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
openai:
  api:
    key: ${OPENAI_API_KEY}
  model:
    default: ${OPENAI_MODEL:gpt-4.1-mini}
# (gpt-4.1-nano, gpt-4.1-mini, ...)

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

