spring:
  application:
    name: chatGraph
  data:
    neo4j:
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1
  model:
    default: gpt-4.1-nano



debug: true
