# application.yml (공통 설정)
spring:
  application:
    name: chatGraph
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

openai:
  api:
    key: ${OPENAI_API_KEY}
  model:
    default: ${OPENAI_MODEL:GPT_4_1_NANO}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}